language: go

arch:
  - amd64

os:
  - linux
  - osx
  - windows

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - 1.16.x
  - 1.17.x

env:
  - GO111MODULE=on

branches:
  only:
    - master

script: 
  - go mod tidy && git diff --exit-code go.mod go.sum
  - go generate
  - go test ${gobuild_args} -v ./...
  #- go get golang.org/x/tools/cmd/cover
  #- go get github.com/mattn/goveralls
  #- go test ${gobuild_args} -v ./... -covermode=count -coverprofile=coverage.out
  #- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

